platform :ios, '16.0'

target 'FunctionGemmaRunner' do
  use_frameworks!

  pod 'MediaPipeTasksGenAI', '~> 0.10.21'
  pod 'MediaPipeTasksGenAIC', '~> 0.10.21'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
